name: Run Command Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run your command
        run: |
          # Replace the following line with the command you want to execute
          echo "Running command every minute on Ubuntu"
          whoami
